services:
  backend:
    build:
      context: ./backend
    working_dir: /app
    volumes:
      - ./backend:/app
      - ~/.m2:/root/.m2
    command: ["./mvnw", "spring-boot:run"]
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=${SPRING_JPA_HIBERNATE_DDL_AUTO}
      - SPRING_DEVTOOLS_RESTART_ENABLED=true


    networks:
      - shared_network
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    networks:
      - shared_network
    depends_on:
      - backend

networks:
  shared_network:
    driver: bridge
